# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addClass.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_addClass(object):
    def setupUi(self, addClass):
        addClass.setObjectName("addClass")
        addClass.resize(653, 418)
        self.centralwidget = QtWidgets.QWidget(addClass)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 801, 601))
        self.widget.setStyleSheet("background-color: rgb(230, 255, 107);\n"
"background-color: rgb(234, 215, 187);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(20, 20, 591, 381))
        self.widget_2.setStyleSheet("background-color: rgb(188, 163, 127);")
        self.widget_2.setObjectName("widget_2")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(240, 320, 151, 31))
        self.pushButton.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 0);")
        self.pushButton.setObjectName("pushButton")
        self.teachers_name_combo = QtWidgets.QComboBox(self.widget_2)
        self.teachers_name_combo.setGeometry(QtCore.QRect(240, 210, 171, 22))
        self.teachers_name_combo.setObjectName("teachers_name_combo")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(50, 200, 171, 41))
        self.label_2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.name_class = QtWidgets.QTextEdit(self.widget_2)
        self.name_class.setGeometry(QtCore.QRect(240, 150, 171, 21))
        self.name_class.setObjectName("name_class")
        self.label = QtWidgets.QLabel(self.widget_2)
        self.label.setGeometry(QtCore.QRect(50, 160, 101, 16))
        self.label.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(180, 10, 241, 71))
        self.label_3.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_3.setObjectName("label_3")
        addClass.setCentralWidget(self.centralwidget)

        self.retranslateUi(addClass)
        QtCore.QMetaObject.connectSlotsByName(addClass)

    def retranslateUi(self, addClass):
        _translate = QtCore.QCoreApplication.translate
        addClass.setWindowTitle(_translate("addClass", "Sınıf Ekleme"))
        self.pushButton.setText(_translate("addClass", "Ekle"))
        self.label_2.setText(_translate("addClass", "Rihberlik hoca :"))
        self.label.setText(_translate("addClass", "Sınıf adı :"))
        self.label_3.setText(_translate("addClass", "Sinif ekleme sayfasi"))
