# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ders_degistirme.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DersDegistirme(object):
    def setupUi(self, DersDegistirme):
        DersDegistirme.setObjectName("DersDegistirme")
        DersDegistirme.resize(359, 150)
        self.centralwidget = QtWidgets.QWidget(DersDegistirme)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 541, 291))
        self.frame.setStyleSheet("background-color: rgb(255, 242, 216);\n"
"background-color: rgb(234, 215, 187);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(10, 10, 341, 131))
        self.widget.setStyleSheet("background-color: rgb(17, 57, 70);\n"
"background-color: rgb(188, 163, 127);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.ders_adi = QtWidgets.QPlainTextEdit(self.widget)
        self.ders_adi.setGeometry(QtCore.QRect(140, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ders_adi.setFont(font)
        self.ders_adi.setStyleSheet("color: rgb(255, 255, 255);")
        self.ders_adi.setObjectName("ders_adi")
        self.arama_btn = QtWidgets.QPushButton(self.widget)
        self.arama_btn.setGeometry(QtCore.QRect(120, 80, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.arama_btn.setFont(font)
        self.arama_btn.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.arama_btn.setObjectName("arama_btn")
        DersDegistirme.setCentralWidget(self.centralwidget)

        self.retranslateUi(DersDegistirme)
        QtCore.QMetaObject.connectSlotsByName(DersDegistirme)

    def retranslateUi(self, DersDegistirme):
        _translate = QtCore.QCoreApplication.translate
        DersDegistirme.setWindowTitle(_translate("DersDegistirme", "Ders Degistirme"))
        self.label.setText(_translate("DersDegistirme", "Ders adı :"))
        self.arama_btn.setText(_translate("DersDegistirme", "Ara"))
