# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ders_egitemn_arama.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ders_egitmen_arama(object):
    def setupUi(self, ders_egitmen_arama):
        ders_egitmen_arama.setObjectName("ders_egitmen_arama")
        ders_egitmen_arama.resize(800, 371)
        self.centralwidget = QtWidgets.QWidget(ders_egitmen_arama)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 801, 371))
        self.widget.setStyleSheet("background-color: rgb(171, 216, 255);\n"
"background-color: rgb(234, 215, 187);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(40, 90, 81, 41))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ders_arama_table = QtWidgets.QTableWidget(self.widget)
        self.ders_arama_table.setGeometry(QtCore.QRect(30, 180, 741, 111))
        self.ders_arama_table.setMinimumSize(QtCore.QSize(0, 0))
        self.ders_arama_table.setObjectName("ders_arama_table")
        self.ders_arama_table.setColumnCount(3)
        self.ders_arama_table.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.ders_arama_table.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ders_arama_table.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.ders_arama_table.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.ders_arama_table.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        item.setFlags(QtCore.Qt.ItemIsSelectable)
        self.ders_arama_table.setItem(0, 1, item)
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(300, 20, 301, 41))
        self.widget_2.setStyleSheet("background-color: rgb(17, 57, 70);")
        self.widget_2.setObjectName("widget_2")
        self.label_2 = QtWidgets.QLabel(self.widget_2)
        self.label_2.setGeometry(QtCore.QRect(50, 0, 201, 41))
        self.label_2.setStyleSheet("font: 75 12pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"font: 75 16pt \"MS Shell Dlg 2\";\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.lesson_names_combo = QtWidgets.QComboBox(self.widget)
        self.lesson_names_combo.setGeometry(QtCore.QRect(120, 100, 221, 31))
        self.lesson_names_combo.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.lesson_names_combo.setObjectName("lesson_names_combo")
        ders_egitmen_arama.setCentralWidget(self.centralwidget)

        self.retranslateUi(ders_egitmen_arama)
        QtCore.QMetaObject.connectSlotsByName(ders_egitmen_arama)

    def retranslateUi(self, ders_egitmen_arama):
        _translate = QtCore.QCoreApplication.translate
        ders_egitmen_arama.setWindowTitle(_translate("ders_egitmen_arama", "MainWindow"))
        self.label.setText(_translate("ders_egitmen_arama", "Dersler :"))
        item = self.ders_arama_table.verticalHeaderItem(0)
        item.setText(_translate("ders_egitmen_arama", "#"))
        item = self.ders_arama_table.horizontalHeaderItem(0)
        item.setText(_translate("ders_egitmen_arama", "Seçilen dersin sınıfı"))
        item = self.ders_arama_table.horizontalHeaderItem(1)
        item.setText(_translate("ders_egitmen_arama", "Dersi veren öğretmen adı"))
        item = self.ders_arama_table.horizontalHeaderItem(2)
        item.setText(_translate("ders_egitmen_arama", "Bu dersi veren öğretmen sorumlu olduğu sınıfın adı"))
        __sortingEnabled = self.ders_arama_table.isSortingEnabled()
        self.ders_arama_table.setSortingEnabled(False)
        self.ders_arama_table.setSortingEnabled(__sortingEnabled)
        self.label_2.setText(_translate("ders_egitmen_arama", "Ders arama sayfası"))
