# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ders_ekleme.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DersEkleme(object):
    def setupUi(self, DersEkleme):
        DersEkleme.setObjectName("DersEkleme")
        DersEkleme.resize(582, 333)
        self.centralwidget = QtWidgets.QWidget(DersEkleme)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, 0, 601, 351))
        self.frame.setStyleSheet("background-color: rgb(255, 242, 216);\n"
"background-color: rgb(234, 215, 187);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(10, 10, 561, 311))
        self.widget.setStyleSheet("background-color: rgb(17, 57, 70);\n"
"background-color: rgb(188, 163, 127);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 20, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.ders_adi = QtWidgets.QPlainTextEdit(self.widget)
        self.ders_adi.setGeometry(QtCore.QRect(200, 20, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.ders_adi.setFont(font)
        self.ders_adi.setStyleSheet("color: rgb(0, 0, 0);\n"
"background-color: rgb(234, 215, 187);")
        self.ders_adi.setObjectName("ders_adi")
        self.ekleme_btn = QtWidgets.QPushButton(self.widget)
        self.ekleme_btn.setGeometry(QtCore.QRect(220, 250, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ekleme_btn.setFont(font)
        self.ekleme_btn.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.ekleme_btn.setObjectName("ekleme_btn")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(10, 140, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        self.teacher_names = QtWidgets.QComboBox(self.widget)
        self.teacher_names.setGeometry(QtCore.QRect(200, 80, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.teacher_names.setFont(font)
        self.teacher_names.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.teacher_names.setObjectName("teacher_names")
        self.class_names = QtWidgets.QComboBox(self.widget)
        self.class_names.setGeometry(QtCore.QRect(200, 140, 181, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.class_names.setFont(font)
        self.class_names.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.class_names.setObjectName("class_names")
        DersEkleme.setCentralWidget(self.centralwidget)

        self.retranslateUi(DersEkleme)
        QtCore.QMetaObject.connectSlotsByName(DersEkleme)

    def retranslateUi(self, DersEkleme):
        _translate = QtCore.QCoreApplication.translate
        DersEkleme.setWindowTitle(_translate("DersEkleme", "Ders Ekleme"))
        self.label.setText(_translate("DersEkleme", "Ders adı :"))
        self.ekleme_btn.setText(_translate("DersEkleme", "Kaydet"))
        self.label_2.setText(_translate("DersEkleme", "Öğretmen adı :"))
        self.label_3.setText(_translate("DersEkleme", "Sınıf adı :"))
