# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ders_ekleme.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DersEkleme(object):
    def setupUi(self, DersEkleme):
        DersEkleme.setObjectName("DersEkleme")
        DersEkleme.resize(397, 182)
        self.centralwidget = QtWidgets.QWidget(DersEkleme)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, 0, 401, 191))
        self.frame.setStyleSheet("background-color: rgb(85, 85, 0);\n"
"background-color: rgb(188, 163, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 40, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.ekleme_btn = QtWidgets.QPushButton(self.frame)
        self.ekleme_btn.setGeometry(QtCore.QRect(140, 120, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ekleme_btn.setFont(font)
        self.ekleme_btn.setStyleSheet("background-color: rgb(17, 57, 70);\n"
"border-color: rgb(0, 170, 0);\n"
"selection-background-color: rgb(0, 85, 0);\n"
"selection-color: rgb(0, 85, 0);\n"
"color: rgb(255, 255, 255);")
        self.ekleme_btn.setObjectName("ekleme_btn")
        self.ders_adi = QtWidgets.QPlainTextEdit(self.frame)
        self.ders_adi.setGeometry(QtCore.QRect(160, 40, 181, 21))
        self.ders_adi.setObjectName("ders_adi")
        self.pushButton = QtWidgets.QPushButton(self.frame)
        self.pushButton.setGeometry(QtCore.QRect(230, 90, 75, 23))
        self.pushButton.setObjectName("pushButton")
        DersEkleme.setCentralWidget(self.centralwidget)

        self.retranslateUi(DersEkleme)
        QtCore.QMetaObject.connectSlotsByName(DersEkleme)

    def retranslateUi(self, DersEkleme):
        _translate = QtCore.QCoreApplication.translate
        DersEkleme.setWindowTitle(_translate("DersEkleme", "Ders Ekleme"))
        self.label.setText(_translate("DersEkleme", "Ders adı :"))
        self.ekleme_btn.setText(_translate("DersEkleme", "Kaydet"))
        self.pushButton.setText(_translate("DersEkleme", "sil"))
