# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'egitmen_islemleri.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_egitmen_islemleri(object):
    def setupUi(self, egitmen_islemleri):
        egitmen_islemleri.setObjectName("egitmen_islemleri")
        egitmen_islemleri.resize(363, 199)
        self.centralwidget = QtWidgets.QWidget(egitmen_islemleri)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 811, 381))
        self.widget.setStyleSheet("background-color: rgb(17, 57, 70);")
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 79, 331, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.add_teacher_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.add_teacher_btn.setStyleSheet("background-color: rgb(17, 57, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.add_teacher_btn.setObjectName("add_teacher_btn")
        self.horizontalLayout_2.addWidget(self.add_teacher_btn)
        self.delete_teacher_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.delete_teacher_btn.setStyleSheet("background-color: rgb(17, 57, 70);\n"
"background-color: rgb(255, 0, 4);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.delete_teacher_btn.setObjectName("delete_teacher_btn")
        self.horizontalLayout_2.addWidget(self.delete_teacher_btn)
        self.edit_teacher_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.edit_teacher_btn.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.edit_teacher_btn.setObjectName("edit_teacher_btn")
        self.horizontalLayout_2.addWidget(self.edit_teacher_btn)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(50, 20, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        egitmen_islemleri.setCentralWidget(self.centralwidget)

        self.retranslateUi(egitmen_islemleri)
        QtCore.QMetaObject.connectSlotsByName(egitmen_islemleri)

    def retranslateUi(self, egitmen_islemleri):
        _translate = QtCore.QCoreApplication.translate
        egitmen_islemleri.setWindowTitle(_translate("egitmen_islemleri", "Öğretmen işlemleri"))
        self.add_teacher_btn.setText(_translate("egitmen_islemleri", "Ekleme"))
        self.delete_teacher_btn.setText(_translate("egitmen_islemleri", "Silme"))
        self.edit_teacher_btn.setText(_translate("egitmen_islemleri", "Değiştirme"))
        self.label.setText(_translate("egitmen_islemleri", "Öğretmen işlemleri"))
