# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ogrenci_islemleri.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(369, 186)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(-10, 0, 811, 371))
        self.widget.setStyleSheet("background-color: rgb(17, 57, 70);")
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(30, 70, 341, 101))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ekleme_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ekleme_btn.setStyleSheet("background-color: rgb(17, 57, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.ekleme_btn.setObjectName("ekleme_btn")
        self.horizontalLayout_2.addWidget(self.ekleme_btn)
        self.silme_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.silme_btn.setStyleSheet("background-color: rgb(17, 57, 70);\n"
"background-color: rgb(255, 0, 4);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.silme_btn.setObjectName("silme_btn")
        self.horizontalLayout_2.addWidget(self.silme_btn)
        self.degistirme_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.degistirme_btn.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 255);")
        self.degistirme_btn.setObjectName("degistirme_btn")
        self.horizontalLayout_2.addWidget(self.degistirme_btn)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(70, 30, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(39, 39, 39);\n"
"color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Ögrenci işlemleri"))
        self.ekleme_btn.setText(_translate("MainWindow", "Ekleme"))
        self.silme_btn.setText(_translate("MainWindow", "Silme"))
        self.degistirme_btn.setText(_translate("MainWindow", "Değiştirme"))
        self.label.setText(_translate("MainWindow", "Öğrenci işlemleri"))
