# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sinif_dersleri.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SinifDersleri(object):
    def setupUi(self, SinifDersleri):
        SinifDersleri.setObjectName("SinifDersleri")
        SinifDersleri.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(SinifDersleri)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(-1, -11, 811, 621))
        self.frame.setStyleSheet("background-color: rgb(188, 163, 127);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setGeometry(QtCore.QRect(80, 180, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.label_9.setObjectName("label_9")
        self.tableWidget = QtWidgets.QTableWidget(self.frame)
        self.tableWidget.setGeometry(QtCore.QRect(80, 220, 611, 351))
        self.tableWidget.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(89, 50, 591, 51))
        self.widget.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.widget.setObjectName("widget")
        self.class_names = QtWidgets.QComboBox(self.widget)
        self.class_names.setGeometry(QtCore.QRect(140, 10, 221, 31))
        self.class_names.setStyleSheet("background-color: rgb(234, 215, 187);\n"
"font: 75 16pt \"MS Serif\";")
        self.class_names.setObjectName("class_names")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(110, 60, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.label_8.setObjectName("label_8")
        SinifDersleri.setCentralWidget(self.centralwidget)

        self.retranslateUi(SinifDersleri)
        QtCore.QMetaObject.connectSlotsByName(SinifDersleri)

    def retranslateUi(self, SinifDersleri):
        _translate = QtCore.QCoreApplication.translate
        SinifDersleri.setWindowTitle(_translate("SinifDersleri", "Sınıf dersleri"))
        self.label_9.setText(_translate("SinifDersleri", " Bilgiler:"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("SinifDersleri", "Ders"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("SinifDersleri", "Öğretmen"))
        self.label_8.setText(_translate("SinifDersleri", "Sınıf adı :"))
