# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sinif_islemleri.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_sinif_islemleri(object):
    def setupUi(self, sinif_islemleri):
        sinif_islemleri.setObjectName("sinif_islemleri")
        sinif_islemleri.resize(367, 194)
        sinif_islemleri.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.centralwidget = QtWidgets.QWidget(sinif_islemleri)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 811, 411))
        self.widget.setStyleSheet("background-color: rgb(17, 57, 70);")
        self.widget.setObjectName("widget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.widget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 89, 351, 91))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ekleme_btn_2 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.ekleme_btn_2.setStyleSheet("background-color: rgb(17, 57, 70);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.ekleme_btn_2.setObjectName("ekleme_btn_2")
        self.horizontalLayout_2.addWidget(self.ekleme_btn_2)
        self.silme_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.silme_btn.setStyleSheet("background-color: rgb(17, 57, 70);\n"
"background-color: rgb(255, 0, 4);\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.silme_btn.setObjectName("silme_btn")
        self.horizontalLayout_2.addWidget(self.silme_btn)
        self.degistirme_btn = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.degistirme_btn.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(0, 0, 255);\n"
"color: rgb(255, 255, 255);")
        self.degistirme_btn.setObjectName("degistirme_btn")
        self.horizontalLayout_2.addWidget(self.degistirme_btn)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(40, 30, 301, 51))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        sinif_islemleri.setCentralWidget(self.centralwidget)

        self.retranslateUi(sinif_islemleri)
        QtCore.QMetaObject.connectSlotsByName(sinif_islemleri)

    def retranslateUi(self, sinif_islemleri):
        _translate = QtCore.QCoreApplication.translate
        sinif_islemleri.setWindowTitle(_translate("sinif_islemleri", "Sınıf işlemleri"))
        self.ekleme_btn_2.setText(_translate("sinif_islemleri", "Ekleme"))
        self.silme_btn.setText(_translate("sinif_islemleri", "Silme"))
        self.degistirme_btn.setText(_translate("sinif_islemleri", "Değiştirme"))
        self.label.setText(_translate("sinif_islemleri", "Sınıf işlemleri"))
