# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'sinif_sorumlusu_degistirme.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_edit_class(object):
    def setupUi(self, edit_class):
        edit_class.setObjectName("edit_class")
        edit_class.resize(576, 462)
        self.centralwidget = QtWidgets.QWidget(edit_class)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 631, 601))
        self.widget.setStyleSheet("background-color: rgb(230, 255, 107);\n"
"background-color: rgb(234, 215, 187);")
        self.widget.setObjectName("widget")
        self.widget_2 = QtWidgets.QWidget(self.widget)
        self.widget_2.setGeometry(QtCore.QRect(10, 10, 551, 441))
        self.widget_2.setStyleSheet("background-color: rgb(188, 163, 127);")
        self.widget_2.setObjectName("widget_2")
        self.bilgileri_goster_2 = QtWidgets.QPushButton(self.widget_2)
        self.bilgileri_goster_2.setGeometry(QtCore.QRect(190, 340, 141, 31))
        self.bilgileri_goster_2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(255, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.bilgileri_goster_2.setObjectName("bilgileri_goster_2")
        self.teachers_name_combo = QtWidgets.QComboBox(self.widget_2)
        self.teachers_name_combo.setGeometry(QtCore.QRect(270, 180, 161, 31))
        self.teachers_name_combo.setStyleSheet("background-color: rgb(234, 215, 187);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.teachers_name_combo.setObjectName("teachers_name_combo")
        self.class_combo = QtWidgets.QComboBox(self.widget_2)
        self.class_combo.setGeometry(QtCore.QRect(270, 110, 161, 31))
        self.class_combo.setStyleSheet("background-color: rgb(234, 215, 187);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.class_combo.setObjectName("class_combo")
        self.pushButton = QtWidgets.QPushButton(self.widget_2)
        self.pushButton.setGeometry(QtCore.QRect(150, 380, 221, 31))
        self.pushButton.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 170, 0);")
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(self.widget_2)
        self.label_3.setGeometry(QtCore.QRect(50, 230, 581, 61))
        self.label_3.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";\n"
"font: 75 14pt \"MS Shell Dlg 2\";\n"
"color: rgb(0, 170, 0);")
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.widget_3 = QtWidgets.QWidget(self.widget_2)
        self.widget_3.setGeometry(QtCore.QRect(59, 180, 191, 31))
        self.widget_3.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.widget_3.setObjectName("widget_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setGeometry(QtCore.QRect(10, 0, 181, 31))
        self.label_2.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label_2.setObjectName("label_2")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        self.widget_4.setGeometry(QtCore.QRect(60, 110, 120, 31))
        self.widget_4.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.widget_4.setObjectName("widget_4")
        self.label = QtWidgets.QLabel(self.widget_4)
        self.label.setGeometry(QtCore.QRect(10, 0, 101, 31))
        self.label.setStyleSheet("font: 75 14pt \"MS Shell Dlg 2\";")
        self.label.setObjectName("label")
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        self.widget_5.setGeometry(QtCore.QRect(100, 20, 361, 41))
        self.widget_5.setStyleSheet("background-color: rgb(234, 215, 187);")
        self.widget_5.setObjectName("widget_5")
        self.label_4 = QtWidgets.QLabel(self.widget_5)
        self.label_4.setGeometry(QtCore.QRect(10, -10, 351, 61))
        self.label_4.setStyleSheet("font: 75 16pt \"MS Shell Dlg 2\";")
        self.label_4.setObjectName("label_4")
        edit_class.setCentralWidget(self.centralwidget)

        self.retranslateUi(edit_class)
        QtCore.QMetaObject.connectSlotsByName(edit_class)

    def retranslateUi(self, edit_class):
        _translate = QtCore.QCoreApplication.translate
        edit_class.setWindowTitle(_translate("edit_class", "Sınıfın sorumlusu değiştirme sayfası"))
        self.bilgileri_goster_2.setText(_translate("edit_class", "Bilgileri goster"))
        self.pushButton.setText(_translate("edit_class", "Degistir"))
        self.label_2.setText(_translate("edit_class", "Sorumlu öğretmen :"))
        self.label.setText(_translate("edit_class", "Sınıf adı :"))
        self.label_4.setText(_translate("edit_class", "Sınıfın sorumlusu değiştirme sayfası"))
