# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'verenDersOgretmentDegistirme.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_veren_ders_degistirme(object):
    def setupUi(self, veren_ders_degistirme):
        veren_ders_degistirme.setObjectName("veren_ders_degistirme")
        veren_ders_degistirme.resize(532, 390)
        veren_ders_degistirme.setToolTipDuration(-1)
        veren_ders_degistirme.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        veren_ders_degistirme.setDocumentMode(False)
        veren_ders_degistirme.setTabShape(QtWidgets.QTabWidget.Rounded)
        veren_ders_degistirme.setDockNestingEnabled(False)
        self.centralwidget = QtWidgets.QWidget(veren_ders_degistirme)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(0, 0, 541, 391))
        self.frame.setStyleSheet("background-color: rgb(255, 242, 216);\n"
"background-color: rgb(234, 215, 187);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.widget = QtWidgets.QWidget(self.frame)
        self.widget.setGeometry(QtCore.QRect(10, 10, 511, 371))
        self.widget.setStyleSheet("background-color: rgb(17, 57, 70);\n"
"background-color: rgb(188, 163, 127);")
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(20, 30, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);")
        self.label.setObjectName("label")
        self.degitir_btn = QtWidgets.QPushButton(self.widget)
        self.degitir_btn.setGeometry(QtCore.QRect(190, 310, 111, 31))
        font = QtGui.QFont()
        font.setFamily("MS Serif")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.degitir_btn.setFont(font)
        self.degitir_btn.setStyleSheet("background-color: rgb(0, 85, 0);\n"
"background-color: rgb(0, 170, 0);\n"
"color: rgb(255, 255, 255);")
        self.degitir_btn.setObjectName("degitir_btn")
        self.teacher_names = QtWidgets.QComboBox(self.widget)
        self.teacher_names.setGeometry(QtCore.QRect(210, 190, 181, 22))
        self.teacher_names.setStyleSheet("background-color: rgb(234, 215, 187);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.teacher_names.setObjectName("teacher_names")
        self.lesson_names = QtWidgets.QComboBox(self.widget)
        self.lesson_names.setGeometry(QtCore.QRect(210, 100, 181, 22))
        self.lesson_names.setStyleSheet("background-color: rgb(234, 215, 187);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.lesson_names.setObjectName("lesson_names")
        self.class_names = QtWidgets.QComboBox(self.widget)
        self.class_names.setGeometry(QtCore.QRect(210, 30, 181, 22))
        self.class_names.setStyleSheet("background-color: rgb(234, 215, 187);\n"
"font: 75 12pt \"MS Shell Dlg 2\";")
        self.class_names.setObjectName("class_names")
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setGeometry(QtCore.QRect(20, 100, 101, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setGeometry(QtCore.QRect(20, 180, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_3.setObjectName("label_3")
        veren_ders_degistirme.setCentralWidget(self.centralwidget)

        self.retranslateUi(veren_ders_degistirme)
        QtCore.QMetaObject.connectSlotsByName(veren_ders_degistirme)

    def retranslateUi(self, veren_ders_degistirme):
        _translate = QtCore.QCoreApplication.translate
        veren_ders_degistirme.setWindowTitle(_translate("veren_ders_degistirme", "Dersi ögretmen degistirme"))
        self.label.setText(_translate("veren_ders_degistirme", "Sınıf adı :"))
        self.degitir_btn.setText(_translate("veren_ders_degistirme", "Degistir"))
        self.label_2.setText(_translate("veren_ders_degistirme", "Ders adı :"))
        self.label_3.setText(_translate("veren_ders_degistirme", "Öğretmen adı :"))
